In [1]:
import numpy as np

# Ex 1

In [61]:
s1 = np.array([0, -0.01])
s2 = np.array([0.01, 0])
t = np.array([4, 5])
a = np.array([-1, 3])

In [63]:
S = np.array([
    s1, s2
])

S_inv = np.linalg.inv(S.T)
a_new = S_inv.dot((a-t).T)
a_new

array([ 200., -500.])

# Check Ex 2

In [14]:
a = np.array([1, 2, 1])
a1 = np.array([9, 15, 1])

b = np.array([2, 1, 1])
b1 = np.array([8, 14, 1])

c = np.array([3, 3, 1])
c1 = np.array([16, 28, 1])

In [17]:
S = np.array([[2, 3, 1], 
              [4, 5, 1], 
              [0, 0, 1]])
a_new = S.dot(a.T)
np.equal(a_new, a1)

array([ True,  True,  True])

In [18]:
b_new = S.dot(b.T)
np.equal(b_new, b1)

array([ True,  True,  True])

In [19]:
c_new = S.dot(c.T)
np.equal(c_new, c1)

array([ True,  True,  True])

# Ex 3

In [64]:
b = np.array([3, 3, 3])
x + 2z = y

SyntaxError: invalid syntax (1532899528.py, line 2)