# Ex 1

In [1]:
import numpy as np

In [2]:
im_size = (1200, 800)
u0, v0 = [i/2 for i in im_size]
angle = np.pi/2

In [3]:
f = round(u0/np.tan(angle/2))
f

600

In [4]:
m = np.array([
    [f, 0, u0],
    [0, f, v0],
    [0, 0, 1]
])
m

array([[600.,   0., 600.],
       [  0., 600., 400.],
       [  0.,   0.,   1.]])

# Ex 2

In [5]:
vec = np.array([3, -1, 10])
f = 500
im_camera = np.array([800, 600])

In [6]:
u0, v0 = im_camera/2
m_cam = np.array([
    [f, 0, u0],
    [0, f, v0],
    [0, 0, 1]
])

vec_cam = m_cam@vec
vec_cam = vec_cam/vec_cam[-1]
vec_cam

array([550., 250.,   1.])

# Ex 3

In [7]:
im_camera = np.array([1200, 800])
u0, v0 = im_camera/2
f = 700
v = 100

In [8]:
alpha = np.arctan((v0-v)/f)
alpha = alpha*180/np.pi
alpha

23.19859051364819

# Ex 4 

In [9]:
np.set_printoptions(suppress=True)

v = 2.5
a = 5

In [10]:
alpha1 = np.pi/2 + np.arctan(a/a)
alpha2 = -np.pi/2 - np.arctan(v/np.sqrt(a**2+a**2))
alpha3 = 0

s1, c1 = np.sin(alpha1), np.cos(alpha1)
s2, c2 = np.sin(alpha2), np.cos(alpha2)
s3, c3 = np.sin(alpha3), np.cos(alpha3)

In [11]:
r = np.array([
    [c1*c3 - c2*s1*s3, -c1*s3 - c2*c3*s1, s1*s2],
    [c3*s1 + c1*c2*s3, c1*c2*c3 - s1*s3, -c1*s2],
    [s2*s3, c3*s2, c2]
])

In [12]:
matr = np.hstack((r.T, -r.T@np.array([5, 5, 2.5]).reshape((3, 1))))
matr

array([[-0.70710678,  0.70710678, -0.        , -0.        ],
       [ 0.23570226,  0.23570226, -0.94280904,  0.        ],
       [-0.66666667, -0.66666667, -0.33333333,  7.5       ]])

In [13]:
inp_vec = np.array([0, 0, 0, 1])

matr@inp_vec

array([-0. ,  0. ,  7.5])